language: c

addons:
    apt:
        packages:
            - gcc-6
            - gcc-mingw-w64
        sources:
            - ubuntu-toolchain-r-test

dist: trusty

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..

script:
    - cd build
    - make
    - make test
